### ISSUE TITLE
Django>=4.0 compatibility

### ISSUE THREAD

**Issue by slamora** [ico-apps/django-importer#59]
django-importer is not compatbile with Django>=0:

```python
django-importer/env/lib/python3.8/site-packages/django/conf/__init__.py:264: RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
  warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)
django-importer/env/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'background_task' defines default_app_config = 'background_task.apps.BackgroundTasksAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)
django-importer/env/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'djimporter' defines default_app_config = 'djimporter.apps.ImporterConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)
 Traceback (most recent call last):
   File "django-importer/env/lib/python3.8/site-packages/compat/__init__.py", line 46, in <module>
     from django.conf.urls import url, include, handler404, handler500
 ImportError: cannot import name 'url' from 'django.conf.urls' (django-importer/env/lib/python3.8/site-packages/django/conf/urls/__init__.py)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "django-importer/env/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
     config._do_configure()
   File "django-importer/env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1074, in _do_configure
     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
   File "django-importer/env/lib/python3.8/site-packages/pluggy/_hooks.py", line 523, in call_historic
     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
   File "django-importer/env/lib/python3.8/site-packages/pluggy/_manager.py", line 119, in _hookexec
     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
   File "django-importer/env/lib/python3.8/site-packages/pluggy/_callers.py", line 138, in _multicall
     raise exception.with_traceback(exception.__traceback__)
   File "django-importer/env/lib/python3.8/site-packages/pluggy/_callers.py", line 102, in _multicall
     res = hook_impl.function(*args)
   File "django-importer/tests/conftest.py", line 80, in pytest_configure
     django.setup()
   File "django-importer/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
     apps.populate(settings.INSTALLED_APPS)
   File "django-importer/env/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
     app_config.import_models()
   File "django-importer/env/lib/python3.8/site-packages/django/apps/config.py", line 304, in import_models
     self.models_module = import_module(models_module_name)
   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "django-importer/env/lib/python3.8/site-packages/background_task/models.py", line 9, in <module>
     from compat import StringIO
   File "django-importer/env/lib/python3.8/site-packages/compat/__init__.py", line 48, in <module>
     from django.conf.urls.defaults import url, include, handler404, handler500  # pyflakes:ignore
 ModuleNotFoundError: No module named 'django.conf.urls.defaults'

```

The source of the problem is on the dependency `django-background-tasks` which depends on [`django-compat`](https://github.com/arteria/django-compat).

**Comment by slamora** [comment]
I've found two forks that fixes compatibility with Django >= 4.0:

1. [django-background-tasks4]()  on pypi as [django-background-tasks4](https://pypi.org/project/django-background-tasks4)
2. [django4-background-tasks](https://github.com/meneses-pt/django-background-tasks/) on pypi as [django4-background-tasks](https://pypi.org/project/django4-background-tasks/)

django-importer tests `PASS` with both of them but I bet for the second option (django**4**-background-tasks) because seems a more active project.
